module.exports = [
	"Der Frauenanteil bei Zuzügen aus dem Ausland liegt bei rund 45%.",
	"In 22 von 23 Wiener Bezirken gibt es Pflegehäuser",
	"Auf der Jasomir-gott-straße sind nur 5 km/h erlaubt",
	"Ein barockes Bürgerhaus aus dem Jahr 1762 steht in der Auersperger-Straße 19",
	"Ein Fahrschein kostete vor 40 Jahren noch 8 Österreichische Schilling. Das wären heute nur 44 Cent",
	"Wien hat 24 Märkte",
	"In Wien existieren 19885 Hektar Grüngebiete",
	"Die Wasserqualität wird an 28 Badestellen gemessen",
	"Dank der Wien-Bibliothek kannst du ein Buch aus dem Jahr 1678 kostenlos im Internet lesen",
	"Wien durchziehen 89 Flüsse und Gräben",
	"Statistisch ist Wien in 250 Zählbezirke unterteil",
	"Über die Stadt verteilt sind 21 militärische Anlagen",
	"Ein Kunstherz kostet 179397 Euro in den Krankenhäusern",
	"Die teuerste Immobilie hat 119 Millionen Euro gekostet, in der Göllner-Gasse",
	"Für Erdwärme sind viele Grundstücke geeignet",
	"Wien bezuschusst 93980 Quadratmeter Solarenergie-Anlagen",
	"Die Elefanten verbrauchen 150000 Liter warmes Wasser zum Duschen",
	"Es gibt über 186078 Bäume in Wien",
	"In Wien gibt es 282313 Gebäude",
	"Affen-Pinscher? Zwerg-Spitz? 55896 Hunde leben in Wien",
	"In den Kindergärten können 104382 Kinder sich austoben",
	"Sag lieber Kaufleute statt Kaufmänner. Das ist geschlechter-gerecht",
	"In ganz Wien stehen 167 Kioske und Würstel-Stände",
	"Die Wiener Linien fahren 2031 Haltestellen an",
	"Noch immer stehen 1162 Telefonzellen in Wien",
	"In 18 Jahren lernen 79434 Schüler in Volksschulen",
	"In 18 Jahren leben 979120 Männer in Wien",
	"In 8 Jahren leben in Wien 59388 Babies und Kleinkinder",
	"Die Wiener sind zu 66% in Österreich geboren",
	"Der Untergrund wird bis zu 99,2 Meter angebohrt und untersucht",
	"40 Bücherereien und 1 Bücherbus gibt es in Wien",
	"Jeff Kinney schrieb die 8 meistgeliehenden Bücher",
	"Die Büchereien melden 40243 neue Bücherwürmer",
	"Dein digitales Wien? 172 Ideen wurden gesammelt",
	"Die Stadtvermesser haben 3921 Orientierungspunkte",
	"Tetanus wird bereits im 3. Monat bei Baies geimpft",
	"Der Vermählungsbrunnen: 1732 erbaut von Corradini",
	"Eingeteilt ist Wien in 11206 statistische Zähleinheiten",
	"Über die Stadt verteilt sind 174 Botschaften und Konsulate",
	"Gut verteilt stehen 12838 Feuerhydranten",
	"Passe deinen Online-Stadtplan aus Wien mit 110 individuelle Malstile an",
	"Der Online-Stadtplan aus Wien bietet 218 zuschaltbare Ebenen an"
];
